#
# Copyright Siemens AG, 2017. Part of the SW360 Portal Project.
#
# Copying and distribution of this file, with or without modification,
# are permitted in any medium without royalty provided the copyright
# notice and this notice are preserved. This file is offered as-is,
# without any warranty.
#

sw360:
  test-user-id: admin@sw360.org
  test-user-password: sw360-admin-password
