#!/usr/bin/env bash
# Copyright Siemens AG, 2015. Part of the SW360 Portal Project.
#
# This program is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License Version 2.0 as published by the
# Free Software Foundation with classpath exception.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License version 2.0 for
# more details.
#
# You should have received a copy of the GNU General Public License along with
# this program (please see the COPYING file); if not, write to the Free
# Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
# 02110-1301, USA.

. ./utilsSW360

groupname=
uploadId=
while getopts g:u: opt; do
  case ${opt} in
    u) uploadId="$OPTARG";;
    g) groupname="$OPTARG";;
  esac
done

checkNotEmpty "$groupname" "$uploadId" || die 1 "bad options $@"

checkNotEmpty "$FOSSUSER" "$FOSSPASS" || die 2 "no user or password known for group='$groupname'"

fossStatus=$( runWithUserAndPass fossupload_status --uploadId "$uploadId" --groupname "$groupname" )

(($?!=0)) && die 1 "fossupload_status failed:" "$fossStatus"

echo "$fossStatus"
