/*
 * Copyright Siemens AG, 2014-2015. Part of the SW360 Portal Project.
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU General Public License Version 2.0 as published by the
 * Free Software Foundation with classpath exception.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License version 2.0 for
 * more details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program (please see the COPYING file); if not, write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301, USA.
 */
package com.siemens.sw360.datahandler.couchdb;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import static com.siemens.sw360.datahandler.common.SW360Constants.KEY_ID;
import static com.siemens.sw360.datahandler.common.SW360Constants.KEY_REV;

/**
 * Mixin class for Jackson serialization into CouchDB. Allows to use objects generated by Thrift directly into CouchDB
 * via Ektorp.
 *
 * @author cedric.bodet@tngtech.com
 */
@JsonPropertyOrder({KEY_ID, KEY_REV})
// Always put _id and _rev upfront. Not required, but serialized objects then look nicer.
@JsonIgnoreProperties({"optionals", "_attachments"})
@SuppressWarnings("unused")
public class DatabaseNestedMixIn {

    @JsonProperty("issetBitfield")
    private byte __isset_bitfield = 0;

}

